/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2024-03-02 13:38:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.Web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Model.User;

public final class indexforadmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/LTWebCuoiKy/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DoAnWeb/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425953470000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1702995907573L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Model.User");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<html lang=\"en\" class=\"light-style layout-menu-fixed layout-compact\" dir=\"ltr\" data-theme=\"theme-default\"\r\n");
      out.write("  data-assetsforadmin-path=\"assetsforadmin/\" data-template=\"vertical-menu-template-free\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Admin</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <meta charset=\"utf-8\" />\r\n");
      out.write("  <meta name=\"viewport\"\r\n");
      out.write("    content=\"width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0\" />\r\n");
      out.write("\r\n");
      out.write("  <title>Dashboard - Analytics | Sneat - Bootstrap 5 HTML Admin Template - Pro</title>\r\n");
      out.write("\r\n");
      out.write("  <meta name=\"description\" content=\"\" />\r\n");
      out.write("\r\n");
      out.write("  <!-- Favicon -->\r\n");
      out.write("  <link rel=\"icon\" type=\"image/x-icon\" href=\"assetsforadmin/img/favicon/favicon.ico\" />\r\n");
      out.write("\r\n");
      out.write("  <!-- Fonts -->\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" />\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin />\r\n");
      out.write("  <link\r\n");
      out.write("    href=\"https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap\"\r\n");
      out.write("    rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"assetsforadmin/vendor/fonts/boxicons.css\" />\r\n");
      out.write("\r\n");
      out.write("  <!-- Core CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"assetsforadmin/vendor/css/core.css\" class=\"template-customizer-core-css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"assetsforadmin/vendor/css/theme-default.css\" class=\"template-customizer-theme-css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"assetsforadmin/css/demo.css\" />\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendors CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"assetsforadmin/vendor/libs/perfect-scrollbar/perfect-scrollbar.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"assetsforadmin/vendor/libs/apex-charts/apex-charts.css\" />\r\n");
      out.write("\r\n");
      out.write("  <!-- Page CSS -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Helpers -->\r\n");
      out.write("  <script src=\"assetsforadmin/vendor/js/helpers.js\"></script>\r\n");
      out.write("  <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->\r\n");
      out.write("  <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->\r\n");
      out.write("  <script src=\"assetsforadmin/js/config.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <!-- Layout wrapper -->\r\n");
      out.write("  <div class=\"layout-wrapper layout-content-navbar\">\r\n");
      out.write("    <div class=\"layout-container\">\r\n");
      out.write("      <!-- Menu -->\r\n");
      out.write("\r\n");
      out.write("      <aside id=\"layout-menu\" class=\"layout-menu menu-vertical menu bg-menu-theme\">\r\n");
      out.write("        <div class=\"app-brand demo\">\r\n");
      out.write("          <a href=\"index.html\" class=\"app-brand-link\">\r\n");
      out.write("            <span class=\"app-brand-logo demo\">\r\n");
      out.write("              <svg width=\"25\" viewBox=\"0 0 25 42\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                xmlns:xlink=\"http://www.w3.org/1999/xlink\">\r\n");
      out.write("                <defs>\r\n");
      out.write("                  <path\r\n");
      out.write("                    d=\"M13.7918663,0.358365126 L3.39788168,7.44174259 C0.566865006,9.69408886 -0.379795268,12.4788597 0.557900856,15.7960551 C0.68998853,16.2305145 1.09562888,17.7872135 3.12357076,19.2293357 C3.8146334,19.7207684 5.32369333,20.3834223 7.65075054,21.2172976 L7.59773219,21.2525164 L2.63468769,24.5493413 C0.445452254,26.3002124 0.0884951797,28.5083815 1.56381646,31.1738486 C2.83770406,32.8170431 5.20850219,33.2640127 7.09180128,32.5391577 C8.347334,32.0559211 11.4559176,30.0011079 16.4175519,26.3747182 C18.0338572,24.4997857 18.6973423,22.4544883 18.4080071,20.2388261 C17.963753,17.5346866 16.1776345,15.5799961 13.0496516,14.3747546 L10.9194936,13.4715819 L18.6192054,7.984237 L13.7918663,0.358365126 Z\"\r\n");
      out.write("                    id=\"path-1\"></path>\r\n");
      out.write("                  <path\r\n");
      out.write("                    d=\"M5.47320593,6.00457225 C4.05321814,8.216144 4.36334763,10.0722806 6.40359441,11.5729822 C8.61520715,12.571656 10.0999176,13.2171421 10.8577257,13.5094407 L15.5088241,14.433041 L18.6192054,7.984237 C15.5364148,3.11535317 13.9273018,0.573395879 13.7918663,0.358365126 C13.5790555,0.511491653 10.8061687,2.3935607 5.47320593,6.00457225 Z\"\r\n");
      out.write("                    id=\"path-3\"></path>\r\n");
      out.write("                  <path\r\n");
      out.write("                    d=\"M7.50063644,21.2294429 L12.3234468,23.3159332 C14.1688022,24.7579751 14.397098,26.4880487 13.008334,28.506154 C11.6195701,30.5242593 10.3099883,31.790241 9.07958868,32.3040991 C5.78142938,33.4346997 4.13234973,34 4.13234973,34 C4.13234973,34 2.75489982,33.0538207 2.37032616e-14,31.1614621 C-0.55822714,27.8186216 -0.55822714,26.0572515 -4.05231404e-15,25.8773518 C0.83734071,25.6075023 2.77988457,22.8248993 3.3049379,22.52991 C3.65497346,22.3332504 5.05353963,21.8997614 7.50063644,21.2294429 Z\"\r\n");
      out.write("                    id=\"path-4\"></path>\r\n");
      out.write("                  <path\r\n");
      out.write("                    d=\"M20.6,7.13333333 L25.6,13.8 C26.2627417,14.6836556 26.0836556,15.9372583 25.2,16.6 C24.8538077,16.8596443 24.4327404,17 24,17 L14,17 C12.8954305,17 12,16.1045695 12,15 C12,14.5672596 12.1403557,14.1461923 12.4,13.8 L17.4,7.13333333 C18.0627417,6.24967773 19.3163444,6.07059163 20.2,6.73333333 C20.3516113,6.84704183 20.4862915,6.981722 20.6,7.13333333 Z\"\r\n");
      out.write("                    id=\"path-5\"></path>\r\n");
      out.write("                </defs>\r\n");
      out.write("                <g id=\"g-app-brand\" stroke=\"none\" stroke-width=\"1\" fill=\"none\" fill-rule=\"evenodd\">\r\n");
      out.write("                  <g id=\"Brand-Logo\" transform=\"translate(-27.000000, -15.000000)\">\r\n");
      out.write("                    <g id=\"Icon\" transform=\"translate(27.000000, 15.000000)\">\r\n");
      out.write("                      <g id=\"Mask\" transform=\"translate(0.000000, 8.000000)\">\r\n");
      out.write("                        <mask id=\"mask-2\" fill=\"white\">\r\n");
      out.write("                          <use xlink:href=\"#path-1\"></use>\r\n");
      out.write("                        </mask>\r\n");
      out.write("                        <use fill=\"#696cff\" xlink:href=\"#path-1\"></use>\r\n");
      out.write("                        <g id=\"Path-3\" mask=\"url(#mask-2)\">\r\n");
      out.write("                          <use fill=\"#696cff\" xlink:href=\"#path-3\"></use>\r\n");
      out.write("                          <use fill-opacity=\"0.2\" fill=\"#FFFFFF\" xlink:href=\"#path-3\"></use>\r\n");
      out.write("                        </g>\r\n");
      out.write("                        <g id=\"Path-4\" mask=\"url(#mask-2)\">\r\n");
      out.write("                          <use fill=\"#696cff\" xlink:href=\"#path-4\"></use>\r\n");
      out.write("                          <use fill-opacity=\"0.2\" fill=\"#FFFFFF\" xlink:href=\"#path-4\"></use>\r\n");
      out.write("                        </g>\r\n");
      out.write("                      </g>\r\n");
      out.write("                      <g id=\"Triangle\"\r\n");
      out.write("                        transform=\"translate(19.000000, 11.000000) rotate(-300.000000) translate(-19.000000, -11.000000) \">\r\n");
      out.write("                        <use fill=\"#696cff\" xlink:href=\"#path-5\"></use>\r\n");
      out.write("                        <use fill-opacity=\"0.2\" fill=\"#FFFFFF\" xlink:href=\"#path-5\"></use>\r\n");
      out.write("                      </g>\r\n");
      out.write("                    </g>\r\n");
      out.write("                  </g>\r\n");
      out.write("                </g>\r\n");
      out.write("              </svg>\r\n");
      out.write("            </span>\r\n");
      out.write("            <span class=\"app-brand-text demo menu-text fw-bold ms-2\">Coffee luck</span>\r\n");
      out.write("          </a>\r\n");
      out.write("\r\n");
      out.write("          <a href=\"javascript:void(0);\" class=\"layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none\">\r\n");
      out.write("            <i class=\"bx bx-chevron-left bx-sm align-middle\"></i>\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"menu-inner-shadow\"></div>\r\n");
      out.write("\r\n");
      out.write("        <ul class=\"menu-inner py-1\">\r\n");
      out.write("          <!-- Dashboards -->\r\n");
      out.write("          <li class=\"menu-item active open\">\r\n");
      out.write("            <a href=\"javascript:void(0);\" class=\"menu-link menu-toggle\">\r\n");
      out.write("              <i class=\"menu-icon tf-icons bx bx-home-circle\"></i>\r\n");
      out.write("              <div data-i18n=\"Dashboards\">Home</div>\r\n");
      out.write("              <div class=\"badge bg-danger rounded-pill ms-auto\"></div>\r\n");
      out.write("            </a>\r\n");
      out.write(" <ul class=\"menu-sub\">\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"XuLyDangNhap\" class=\"menu-link\">\r\n");
      out.write("                  <div data-i18n=\"Account\">Statistic</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("          <!-- Layouts -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          <!-- Front Pages -->\r\n");
      out.write("\r\n");
      out.write("          <!-- Apps -->\r\n");
      out.write("\r\n");
      out.write("          <!-- Pages -->\r\n");
      out.write("          <li class=\"menu-item\">\r\n");
      out.write("            <a href=\"EditAdmin.jsp\" class=\"menu-link menu-toggle\">\r\n");
      out.write("              <i class=\"menu-icon tf-icons bx bx-dock-top\"></i>\r\n");
      out.write("              <div >Account Settings</div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"menu-sub\">\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"XuLyAdmin\" class=\"menu-link\">\r\n");
      out.write("                  <div >Account</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"pages-account-settings-notifications.html\" class=\"menu-link\">\r\n");
      out.write("                  <div data-i18n=\"Notifications\">Notifications</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"pages-account-settings-connections.html\" class=\"menu-link\">\r\n");
      out.write("                  <div data-i18n=\"Connections\">Connections</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("           <li class=\"menu-item\">\r\n");
      out.write("            <a href=\"EditAdmin.jsp\" class=\"menu-link menu-toggle\">\r\n");
      out.write("              <i class=\"menu-icon tf-icons bx bx-dock-top\"></i>\r\n");
      out.write("              <div >Manager user</div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"menu-sub\">\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"XuLyAdminUser\" class=\"menu-link\">\r\n");
      out.write("                  <div >Account</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"pages-account-settings-notifications.html\" class=\"menu-link\">\r\n");
      out.write("                  <div data-i18n=\"Notifications\">Notifications</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"pages-account-settings-connections.html\" class=\"menu-link\">\r\n");
      out.write("                  <div data-i18n=\"Connections\">Connections</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"menu-item\">\r\n");
      out.write("            <a href=\"EditAdmin.jsp\" class=\"menu-link menu-toggle\">\r\n");
      out.write("              <i class=\"menu-icon tf-icons bx bx-dock-top\"></i>\r\n");
      out.write("              <div >Manager Product</div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"menu-sub\">\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"XuLyAdminProduct\" class=\"menu-link\">\r\n");
      out.write("                  <div >Product</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"pages-account-settings-notifications.html\" class=\"menu-link\">\r\n");
      out.write("                  <div data-i18n=\"Notifications\">Notifications</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"pages-account-settings-connections.html\" class=\"menu-link\">\r\n");
      out.write("                  <div data-i18n=\"Connections\">Connections</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"menu-item\">\r\n");
      out.write("            <a href=\"EditAdmin.jsp\" class=\"menu-link menu-toggle\">\r\n");
      out.write("              <i class=\"menu-icon tf-icons bx bx-dock-top\"></i>\r\n");
      out.write("              <div >Manager Comment</div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"menu-sub\">\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"XuLyAdminComment\" class=\"menu-link\">\r\n");
      out.write("                  <div >Comment</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"pages-account-settings-notifications.html\" class=\"menu-link\">\r\n");
      out.write("                  <div data-i18n=\"Notifications\">Notifications</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"pages-account-settings-connections.html\" class=\"menu-link\">\r\n");
      out.write("                  <div data-i18n=\"Connections\">Connections</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"menu-item\">\r\n");
      out.write("            <a href=\"EditAdmin.jsp\" class=\"menu-link menu-toggle\">\r\n");
      out.write("              <i class=\"menu-icon tf-icons bx bx-dock-top\"></i>\r\n");
      out.write("              <div >Manager Category</div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"menu-sub\">\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"XuLyAdminCategory\" class=\"menu-link\">\r\n");
      out.write("                  <div >Category</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"pages-account-settings-notifications.html\" class=\"menu-link\">\r\n");
      out.write("                  <div data-i18n=\"Notifications\">Notifications</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"pages-account-settings-connections.html\" class=\"menu-link\">\r\n");
      out.write("                  <div data-i18n=\"Connections\">Connections</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"menu-item\">\r\n");
      out.write("            <a href=\"EditAdmin.jsp\" class=\"menu-link menu-toggle\">\r\n");
      out.write("              <i class=\"menu-icon tf-icons bx bx-dock-top\"></i>\r\n");
      out.write("              <div >Manager Order</div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"menu-sub\">\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"XuLyAdminOrder\" class=\"menu-link\">\r\n");
      out.write("                  <div >OrderNotCheckout</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"XuLyAdminOrderCheckOut\" class=\"menu-link\">\r\n");
      out.write("                  <div >OrderCheckout</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"pages-account-settings-connections.html\" class=\"menu-link\">\r\n");
      out.write("                  <div data-i18n=\"Connections\">Connections</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          <!-- Components -->\r\n");
      out.write("\r\n");
      out.write("          <!-- Forms & Tables -->\r\n");
      out.write("          <li class=\"menu-header small text-uppercase\"><span class=\"menu-header-text\">Forms &amp; Tables</span></li>\r\n");
      out.write("          <!-- Forms -->\r\n");
      out.write("          <li class=\"menu-item\">\r\n");
      out.write("            <a href=\"javascript:void(0);\" class=\"menu-link menu-toggle\">\r\n");
      out.write("              <i class=\"menu-icon tf-icons bx bx-detail\"></i>\r\n");
      out.write("              <div data-i18n=\"Form Elements\">Form Elements</div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"menu-sub\">\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"forms-basic-inputs.html\" class=\"menu-link\">\r\n");
      out.write("                  <div data-i18n=\"Basic Inputs\">Basic Inputs</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"forms-input-groups.html\" class=\"menu-link\">\r\n");
      out.write("                  <div data-i18n=\"Input groups\">Input groups</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"menu-item\">\r\n");
      out.write("            <a href=\"javascript:void(0);\" class=\"menu-link menu-toggle\">\r\n");
      out.write("              <i class=\"menu-icon tf-icons bx bx-detail\"></i>\r\n");
      out.write("              <div data-i18n=\"Form Layouts\">Form Layouts</div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"menu-sub\">\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"form-layouts-vertical.html\" class=\"menu-link\">\r\n");
      out.write("                  <div data-i18n=\"Vertical Form\">Vertical Form</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"form-layouts-horizontal.html\" class=\"menu-link\">\r\n");
      out.write("                  <div data-i18n=\"Horizontal Form\">Horizontal Form</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <!-- Form Validation -->\r\n");
      out.write("\r\n");
      out.write("          <!-- Tables -->\r\n");
      out.write("          <li class=\"menu-item\">\r\n");
      out.write("            <a href=\"tables-basic.html\" class=\"menu-link\">\r\n");
      out.write("              <i class=\"menu-icon tf-icons bx bx-table\"></i>\r\n");
      out.write("              <div data-i18n=\"Tables\">Tables</div>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <!-- Data Tables -->\r\n");
      out.write("\r\n");
      out.write("          <!-- Misc -->\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("      </aside>\r\n");
      out.write("      <!-- / Menu -->\r\n");
      out.write("\r\n");
      out.write("      <!-- Layout container -->\r\n");
      out.write("      <div class=\"layout-page\">\r\n");
      out.write("        <!-- Navbar -->\r\n");
      out.write("\r\n");
      out.write("        <nav\r\n");
      out.write("          class=\"layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme\"\r\n");
      out.write("          id=\"layout-navbar\">\r\n");
      out.write("          <div class=\"layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none\">\r\n");
      out.write("            <a class=\"nav-item nav-link px-0 me-xl-4\" href=\"javascript:void(0)\">\r\n");
      out.write("              <i class=\"bx bx-menu bx-sm\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"navbar-nav-right d-flex align-items-center\" id=\"navbar-collapse\">\r\n");
      out.write("            <!-- Search -->\r\n");
      out.write("            <div class=\"navbar-nav align-items-center\">\r\n");
      out.write("              <div class=\"nav-item d-flex align-items-center\">\r\n");
      out.write("                <i class=\"bx bx-search fs-4 lh-0\"></i>\r\n");
      out.write("                <input type=\"text\" class=\"form-control border-0 shadow-none ps-1 ps-sm-2\" placeholder=\"Search...\"\r\n");
      out.write("                  aria-label=\"Search...\" />\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /Search -->\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"navbar-nav flex-row align-items-center ms-auto\">\r\n");
      out.write("              <!-- Place this tag where you want the button to render. -->\r\n");
      out.write("           <li class=\"nav-item lh-1 me-3\">\r\n");
      out.write("              ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <!-- User -->\r\n");
      out.write("              <li class=\"nav-item navbar-dropdown dropdown-user dropdown\">\r\n");
      out.write("                <a class=\"nav-link dropdown-toggle hide-arrow\" href=\"javascript:void(0);\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                  <div class=\"avatar avatar-online\">\r\n");
      out.write("                    <img src=\"assetsforadmin/img/avatars/1.png\" alt class=\"w-px-40 h-auto rounded-circle\" />\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("                <ul class=\"dropdown-menu dropdown-menu-end\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a class=\"dropdown-item\" href=\"#\">\r\n");
      out.write("                      <div class=\"d-flex\">\r\n");
      out.write("                        <div class=\"flex-shrink-0 me-3\">\r\n");
      out.write("                          <div class=\"avatar avatar-online\">\r\n");
      out.write("                            <img src=\"assetsforadmin/img/avatars/1.png\" alt class=\"w-px-40 h-auto rounded-circle\" />\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"flex-grow-1\">\r\n");
      out.write("                          <span class=\"fw-medium d-block\">John Doe</span>\r\n");
      out.write("                          <small class=\"text-muted\">Admin</small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a class=\"dropdown-item\" href=\"#\">\r\n");
      out.write("                      <i class=\"bx bx-user me-2\"></i>\r\n");
      out.write("                      <span class=\"align-middle\">My Profile</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a class=\"dropdown-item\" href=\"#\">\r\n");
      out.write("                      <i class=\"bx bx-cog me-2\"></i>\r\n");
      out.write("                      <span class=\"align-middle\">Settings</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a class=\"dropdown-item\" href=\"#\">\r\n");
      out.write("                      <span class=\"d-flex align-items-center align-middle\">\r\n");
      out.write("                        <i class=\"flex-shrink-0 bx bx-credit-card me-2\"></i>\r\n");
      out.write("                        <span class=\"flex-grow-1 align-middle ms-1\">Billing</span>\r\n");
      out.write("                        <span class=\"flex-shrink-0 badge badge-center rounded-pill bg-danger w-px-20 h-px-20\">4</span>\r\n");
      out.write("                      </span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a class=\"dropdown-item\" href=\"javascript:void(0);\">\r\n");
      out.write("                      <i class=\"bx bx-power-off me-2\"></i>\r\n");
      out.write("                      <span class=\"align-middle\">Log Out</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              <!--/ User -->\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("    <div id=\"piechart\" style=\"width: 900px; height: 500px;position:relative;left:100px\"></div>\r\n");
      out.write("    <div id=\"donutchart\" style=\"width: 900px; height: 500px;position:relative;top:10px;left:100px\"></div>\r\n");
      out.write("\r\n");
      out.write("        <!-- / Navbar -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Content wrapper -->\r\n");
      out.write("         <div class=\"content-wrapper\">\r\n");
      out.write("          <!-- Content -->\r\n");
      out.write("\r\n");
      out.write("          <div class=\"container-xxl flex-grow-1 container-p-y\">\r\n");
      out.write("            <h4 class=\"py-3 mb-4\"><span class=\"text-muted fw-light\">Tables /</span> Basic Tables</h4>\r\n");
      out.write("\r\n");
      out.write("            <!-- Basic Bootstrap Table -->\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <h5 class=\"card-header\">List of Sell</h5>\r\n");
      out.write("              			<p>Số lượng sản phẩm bán được :");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalsell}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("              			\r\n");
      out.write("              <div class=\"col-md-6 pb-4\">\r\n");
      out.write("                        <div class=\"d-flex\">\r\n");
      out.write("                            <select class=\"form-control\" onchange=\"location = this.value;\">\r\n");
      out.write("                                <option hidden>Featured</option>\r\n");
      out.write("                                \r\n");
      out.write("                        \r\n");
      out.write("                            <optgroup label = \"Thứ tự\">\r\n");
      out.write("                                <option value=\"XuLyHDOrder?action=MQuantity\">Bán nhiều nhất</option>\r\n");
      out.write("                                <option value=\"XuLyHDOrder?action=LQuantity\">Bán ít nhất</option>\r\n");
      out.write("                                <option value=\"XuLyHDOrder?action=MMoney\">Bán giá lớn nhất</option>\r\n");
      out.write("                                <option value=\"XuLyHDOrder?action=LMoney\">Bán giá nhỏ nhất</option>\r\n");
      out.write("                                \r\n");
      out.write("                                </optgroup>\r\n");
      out.write("                            \r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("              <div class=\"table-responsive text-nowrap\">\r\n");
      out.write("                <table id=\"tabledata\" class=\"table\">\r\n");
      out.write("                  <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <th>ID</th>\r\n");
      out.write("						<th>Product</th>\r\n");
      out.write("						<th>Quantity</th>\r\n");
      out.write("						<th>Total</th>\r\n");
      out.write("						<th>Buyer</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                  </thead>\r\n");
      out.write("                  <tbody class=\"table-border-bottom-0\">\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("					</tbody>\r\n");
      out.write("					</table>\r\n");
      out.write("					\r\n");
      out.write("\r\n");
      out.write("                      <!--/ Responsive Table -->\r\n");
      out.write("<button onclick=\"exportTableToExcel('tabledata', 'user_data')\">Export Table Data To Excel File</button>\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("              <!-- / Content -->\r\n");
      out.write("\r\n");
      out.write("              <!-- Footer -->\r\n");
      out.write("\r\n");
      out.write("              <!-- / Footer -->\r\n");
      out.write("\r\n");
      out.write("              <div class=\"content-backdrop fade\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Content wrapper -->\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- / Content -->\r\n");
      out.write("\r\n");
      out.write("          <!-- Footer -->\r\n");
      out.write("          \r\n");
      out.write("          <!-- / Footer -->\r\n");
      out.write("\r\n");
      out.write("          <div class=\"content-backdrop fade\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Content wrapper -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- / Layout page -->\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Overlay -->\r\n");
      out.write("    <div class=\"layout-overlay layout-menu-toggle\"></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- / Layout wrapper -->\r\n");
      out.write("\r\n");
      out.write("  <div class=\"buy-now\">\r\n");
      out.write("   \r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Core JS -->\r\n");
      out.write("  <!-- build:js assetsforadmin/vendor/js/core.js -->\r\n");
      out.write("  \r\n");
      out.write("  <script src=\"assetsforadmin/vendor/libs/jquery/jquery.js\"></script>\r\n");
      out.write("  <script src=\"assetsforadmin/vendor/libs/popper/popper.js\"></script>\r\n");
      out.write("  <script src=\"assetsforadmin/vendor/js/bootstrap.js\"></script>\r\n");
      out.write("  <script src=\"assetsforadmin/vendor/libs/perfect-scrollbar/perfect-scrollbar.js\"></script>\r\n");
      out.write("  <script src=\"assetsforadmin/vendor/js/menu.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- endbuild -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendors JS -->\r\n");
      out.write("  <script src=\"assetsforadmin/vendor/libs/apex-charts/apexcharts.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Main JS -->\r\n");
      out.write("  <script src=\"assetsforadmin/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Page JS -->\r\n");
      out.write("  <script src=\"assetsforadmin/js/dashboards-analytics.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Place this tag in your head or just before your close body tag. -->\r\n");
      out.write("  <script async defer src=\"https://buttons.github.io/buttons.js\"></script>\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write(" <script>\r\n");
      out.write("  function exportTableToExcel(tableID, filename = '') {\r\n");
      out.write("    var downloadLink;\r\n");
      out.write("    var dataType = 'application/vnd.ms-excel';\r\n");
      out.write("    var tableSelect = document.getElementById(tableID);\r\n");
      out.write("\r\n");
      out.write("    // Clone the table to prevent modification of the original table\r\n");
      out.write("    var clonedTable = tableSelect.cloneNode(true);\r\n");
      out.write("\r\n");
      out.write("    // Replace image sources with base64-encoded data\r\n");
      out.write("    var images = clonedTable.getElementsByTagName('img');\r\n");
      out.write("    for (var i = 0; i < images.length; i++) {\r\n");
      out.write("      var src = images[i].getAttribute('src');\r\n");
      out.write("      if (src.startsWith('data:image')) continue; // Already in base64 format\r\n");
      out.write("      var canvas = document.createElement('canvas');\r\n");
      out.write("      var ctx = canvas.getContext('2d');\r\n");
      out.write("      var img = new Image();\r\n");
      out.write("      img.src = src;\r\n");
      out.write("      canvas.width = img.width;\r\n");
      out.write("      canvas.height = img.height;\r\n");
      out.write("      ctx.drawImage(img, 0, 0, img.width, img.height);\r\n");
      out.write("      var base64Data = canvas.toDataURL('image/png');\r\n");
      out.write("      images[i].setAttribute('src', base64Data);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    var tableHTML = clonedTable.outerHTML.replace(/ /g, '%20');\r\n");
      out.write("\r\n");
      out.write("    // Specify file name\r\n");
      out.write("    filename = filename ? filename + '.xls' : 'excel_data.xls';\r\n");
      out.write("\r\n");
      out.write("    // Create download link element\r\n");
      out.write("    downloadLink = document.createElement('a');\r\n");
      out.write("\r\n");
      out.write("    document.body.appendChild(downloadLink);\r\n");
      out.write("\r\n");
      out.write("    if (navigator.msSaveOrOpenBlob) {\r\n");
      out.write("      var blob = new Blob(['\\ufeff', tableHTML], {\r\n");
      out.write("        type: dataType\r\n");
      out.write("      });\r\n");
      out.write("      navigator.msSaveOrOpenBlob(blob, filename);\r\n");
      out.write("    } else {\r\n");
      out.write("      // Create a link to the file\r\n");
      out.write("      downloadLink.href = 'data:' + dataType + ', ' + tableHTML;\r\n");
      out.write("\r\n");
      out.write("      // Setting the file name\r\n");
      out.write("      downloadLink.download = filename;\r\n");
      out.write("\r\n");
      out.write("      // Triggering the function\r\n");
      out.write("      downloadLink.click();\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write(" <script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("      google.charts.load('current', {'packages':['corechart']});\r\n");
      out.write("      google.charts.setOnLoadCallback(drawChart);\r\n");
      out.write("\r\n");
      out.write("      function drawChart() {\r\n");
      out.write("    	    var coffee1 = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${coffeesell}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("; // Giả sử coffeesell1 là một biến số từ JSP\r\n");
      out.write("    	    var milktea1 = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${milkteasell}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("    	    var juice1 = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${juicesell}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\r\n");
      out.write("    	    var coffee2 = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${coffeesell2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("; // Giả sử coffeesell2 là một biến số từ JSP\r\n");
      out.write("    	    var milktea2 = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${milkteasell2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("    	    var juice2 = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${juicesell2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\r\n");
      out.write("    	    // Biểu đồ Pie thứ nhất\r\n");
      out.write("    	    var data1 = google.visualization.arrayToDataTable([\r\n");
      out.write("    	        ['Task', 'Hours per Day'],\r\n");
      out.write("    	        ['Coffee', coffee1],\r\n");
      out.write("    	        ['MilkTea', milktea1],\r\n");
      out.write("    	        ['Juice', juice1],\r\n");
      out.write("    	    ]);\r\n");
      out.write("\r\n");
      out.write("    	    var options1 = {\r\n");
      out.write("    	        title: 'Product Sell 1'\r\n");
      out.write("    	    };\r\n");
      out.write("\r\n");
      out.write("    	    var chart1 = new google.visualization.PieChart(document.getElementById('piechart'));\r\n");
      out.write("    	    chart1.draw(data1, options1);\r\n");
      out.write("\r\n");
      out.write("    	    // Biểu đồ Pie thứ hai\r\n");
      out.write("    	    var data2 = google.visualization.arrayToDataTable([\r\n");
      out.write("    	        ['Task', 'Hours per Day'],\r\n");
      out.write("    	        ['Coffee', 10],\r\n");
      out.write("    	        ['MilkTea', 11],\r\n");
      out.write("    	        ['Juice', 12],\r\n");
      out.write("    	    ]);\r\n");
      out.write("\r\n");
      out.write("    	    var options2 = {\r\n");
      out.write("    	        title: 'Product Sell 2'\r\n");
      out.write("    	    };\r\n");
      out.write("\r\n");
      out.write("    	    var chart2 = new google.visualization.PieChart(document.getElementById('chart'));\r\n");
      out.write("    	    chart2.draw(data2, options2);\r\n");
      out.write("    	\r\n");
      out.write("      }\r\n");
      out.write("      </script>\r\n");
      out.write(" <script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("      google.charts.load('current', {'packages':['corechart']});\r\n");
      out.write("      google.charts.setOnLoadCallback(drawChart);\r\n");
      out.write("\r\n");
      out.write("      function drawChart() {\r\n");
      out.write("    	  var coffee = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${coffeesell}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("; // Giả sử workHours là một biến số từ JSP\r\n");
      out.write("          var milktea = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${milkteasell}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("          var juice = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${juicesell}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("        var data = google.visualization.arrayToDataTable([\r\n");
      out.write("          ['Task', 'Hours per Day'],\r\n");
      out.write("          ['Coffee',     coffee],\r\n");
      out.write("          ['MilkTea',      milktea],\r\n");
      out.write("          ['Juice',  juice],\r\n");
      out.write("         \r\n");
      out.write("        ]);\r\n");
      out.write("\r\n");
      out.write("        var options = {\r\n");
      out.write("          title: 'Product Sell'\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        var chart = new google.visualization.PieChart(document.getElementById('piechart'));\r\n");
      out.write("\r\n");
      out.write("        chart.draw(data, options);\r\n");
      out.write("      }\r\n");
      out.write("      </script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("      google.charts.load(\"current\", {packages:[\"corechart\"]});\r\n");
      out.write("      google.charts.setOnLoadCallback(drawChart);\r\n");
      out.write("      function drawChart() {\r\n");
      out.write("    	  var coffee = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${coffeem}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("; // Giả sử workHours là một biến số từ JSP\r\n");
      out.write("          var milktea = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${milkteam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("          var juice = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${juicem}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("        var data = google.visualization.arrayToDataTable([\r\n");
      out.write("          ['Task', 'Hours per Day'],\r\n");
      out.write("          ['Coffee',     coffee],\r\n");
      out.write("          ['MilkTea',      milktea],\r\n");
      out.write("          ['Juice',  juice],\r\n");
      out.write("        ]);\r\n");
      out.write("\r\n");
      out.write("        var options = {\r\n");
      out.write("          title: 'Money Sell',\r\n");
      out.write("          pieHole: 0.4,\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        var chart = new google.visualization.PieChart(document.getElementById('donutchart'));\r\n");
      out.write("        chart.draw(data, options);\r\n");
      out.write("      }\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("    ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/Web/indexforadmin.jsp(370,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.userloginA.name}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<p style=\"position:relative;top:8px\">Chào ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userloginA.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/<a href=\"DangNhap.jsp\" style=\"text-decoration:none\">LogOut</a></p>    ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("        <a href=\"DangNhap.jsp\" style=\"text-decoration:none\">Log in</a>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/Web/indexforadmin.jsp(486,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty sessionScope.totalsell}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  ");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/Web/indexforadmin.jsp(487,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("Sell");
      // /WEB-INF/Web/indexforadmin.jsp(487,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/Web/indexforadmin.jsp(487,2) '${listsell}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listsell}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("  \r\n");
            out.write("\r\n");
            out.write("						<tr>\r\n");
            out.write("							\r\n");
            out.write("						<td>");
            if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("							<td>");
            if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("							<td>");
            if (_jspx_meth_c_005fout_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("							<td>");
            if (_jspx_meth_c_005fout_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("							<td>");
            if (_jspx_meth_c_005fout_005f4(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("                     \r\n");
            out.write("                    </tr>\r\n");
            out.write("                    <tr>\r\n");
            out.write("                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/Web/indexforadmin.jsp(491,10) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Sell.orderid}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/Web/indexforadmin.jsp(492,11) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Sell.productname}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f2_reused = false;
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/Web/indexforadmin.jsp(493,11) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Sell.quantity}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      _jspx_th_c_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f3_reused = false;
    try {
      _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/Web/indexforadmin.jsp(494,11) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Sell.totalprice}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
      if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      _jspx_th_c_005fout_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f4_reused = false;
    try {
      _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/Web/indexforadmin.jsp(495,11) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Sell.username}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
      if (_jspx_th_c_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
      _jspx_th_c_005fout_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f4_reused);
    }
    return false;
  }
}
