/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2024-02-29 02:54:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.Web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import DAO.NgonNguDAO;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/LTWebCuoiKy/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DoAnWeb/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425953470000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1702995907573L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("DAO.NgonNguDAO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 Map<String,String> showlanguage = new NgonNguDAO().vietnamLanguage();
   String lang = (String) session.getAttribute("lang");
   if(lang!=null){
	   if(lang.equals("Vietnamese")){
		   showlanguage = new NgonNguDAO().vietnamLanguage();
	   }else if(lang.equals("English")){
		   showlanguage = new NgonNguDAO().englishLanguage();
		   
	   }
   }


      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <title>Coffee luck</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"apple-touch-icon\" href=\"assets/img/apple-icon.png\">\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\">\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/templatemo.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/custom.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/Translate.css\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- Load fonts style after rendering the layout styles -->\r\n");
      out.write("    <link rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/fontawesome.min.css\">\r\n");
      out.write("          <link rel=\"shortcut icon\" href=\"favicon.png\">\r\n");
      out.write("      <script src = \"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js\"\r\n");
      out.write("   Integrity = \"sha512-STof4xm1wgkfm7heWqFJVn58Hm3EtS31XFaagaa8VMReCXAkQnJZ+jEy8PCC/iT18dFy95WcExNHFTqLyp72eQ==\"\r\n");
      out.write("   crossorigin = \"anonymous\" referrerpolicy = \"no-referrer\"> </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"dark-class\">\r\n");
      out.write("  <!-- Start Top Nav -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg bg-dark navbar-light d-none d-lg-block\" id=\"templatemo_nav_top\">\r\n");
      out.write("        <div class=\"container text-light\">\r\n");
      out.write("            <div class=\"w-100 d-flex justify-content-between\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <i class=\"fa fa-envelope mx-2\"></i>\r\n");
      out.write("                    <a class=\"navbar-sm-brand text-light text-decoration-none\"\r\n");
      out.write("                      href=\"mailto:info@company.com\">info@company.com</a>\r\n");
      out.write("                    <i class=\"fa fa-phone mx-2\"></i>\r\n");
      out.write("                    <a class=\"navbar-sm-brand text-light text-decoration-none\" href=\"tel:010-020-0340\">010-020-0340</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <a class=\"text-light\" href=\"https://fb.com/templatemo\" target=\"_blank\" rel=\"sponsored\"><i\r\n");
      out.write("                          class=\"fab fa-facebook-f fa-sm fa-fw me-2\"></i></a>\r\n");
      out.write("                    <a class=\"text-light\" href=\"https://www.instagram.com/\" target=\"_blank\"><i\r\n");
      out.write("                          class=\"fab fa-instagram fa-sm fa-fw me-2\"></i></a>\r\n");
      out.write("                    <a class=\"text-light\" href=\"https://twitter.com/\" target=\"_blank\"><i\r\n");
      out.write("                          class=\"fab fa-twitter fa-sm fa-fw me-2\"></i></a>\r\n");
      out.write("                    <a class=\"text-light\" href=\"https://www.linkedin.com/\" target=\"_blank\"><i\r\n");
      out.write("                          class=\"fab fa-linkedin fa-sm fa-fw\"></i></a>\r\n");
      out.write("                          <!-- <label class = \"toggleButton\">\r\n");
      out.write("      <input type = \"checkbox\" id = \"toggle\">\r\n");
      out.write("      <div class = \"roundButton circle\" ></div>\r\n");
      out.write("   </label> -->\r\n");
      out.write("                </div>\r\n");
      out.write("    <a role=\"menuitem\" href=\"DaNgonNguindex?lang=Vietnamese\"><img src=\"assets/img/vietnam.png\" style=\"position:absolute;left:1140px;top:7px\"></a>\r\n");
      out.write("<a role=\"menuitem\" href=\"DaNgonNguindex?lang=English\"><img src=\"assets/img/united-states.png\" style=\"position:absolute;left:1180px;top:7px\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div id='google_translate_element'></div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Close Top Nav -->\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("                   \r\n");
      out.write("                     \r\n");
      out.write("                  \r\n");
      out.write("             \r\n");
      out.write("              \r\n");
      out.write("    <!-- Close Header -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Modal -->\r\n");
      out.write("    <div class=\"modal fade bg-white\" id=\"templatemo_search\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("      aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog modal-lg\" role=\"document\">\r\n");
      out.write("            <div class=\"w-100 pt-1 mb-5 text-right\">\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form action=\"\" method=\"get\" class=\"modal-content modal-body border-0 p-0\">\r\n");
      out.write("                <div class=\"input-group mb-2\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"inputModalSearch\" name=\"q\" placeholder=\"Search ...\">\r\n");
      out.write("                    <button type=\"submit\" class=\"input-group-text bg-success text-light\">\r\n");
      out.write("                        <i class=\"fa fa-fw fa-search text-white\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Start Banner Hero -->\r\n");
      out.write("    <div id=\"template-mo-zay-hero-carousel\" class=\"carousel slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("        <ol class=\"carousel-indicators\">\r\n");
      out.write("            <li data-bs-target=\"#template-mo-zay-hero-carousel\" data-bs-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("            <li data-bs-target=\"#template-mo-zay-hero-carousel\" data-bs-slide-to=\"1\"></li>\r\n");
      out.write("            <li data-bs-target=\"#template-mo-zay-hero-carousel\" data-bs-slide-to=\"2\"></li>\r\n");
      out.write("        </ol>\r\n");
      out.write("        <div class=\"carousel-inner\">\r\n");
      out.write("            <div class=\"carousel-item active\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row p-5\">\r\n");
      out.write("                        <div class=\"mx-auto col-md-8 col-lg-6 order-lg-last\">\r\n");
      out.write("                            <img  src=\"./assets/img/Banner1.jpg\" style=\"width:500px\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-6 mb-0 d-flex align-items-center\">\r\n");
      out.write("                            <div class=\"text-align-left align-self-center\">\r\n");
      out.write("                                <h2 >");
      out.print(showlanguage.get("index.banner1.1"));
      out.write("</h2>\r\n");
      out.write("                               \r\n");
      out.write("                                <p>\r\n");
      out.write("                                    ");
      out.print(showlanguage.get("index.banner1.2"));
      out.write("\r\n");
      out.write("                                </p>\r\n");
      out.write("                                \r\n");
      out.write("                               <span style=\"position:relative;left:110px;font-size:26px\">");
      out.print(showlanguage.get("index.banner1.3"));
      out.write("</span>\r\n");
      out.write("                               <div class=\"time-container\">\r\n");
      out.write("      <div class=\"time\"><p>");
      out.print(showlanguage.get("index.banner1.4"));
      out.write("</p><span id=\"days\">00</span></div>\r\n");
      out.write("      <div class=\"time\"><p>");
      out.print(showlanguage.get("index.banner1.5"));
      out.write("</p><span id=\"hours\">00</span></div>\r\n");
      out.write("      <div class=\"time\"><p>");
      out.print(showlanguage.get("index.banner1.6"));
      out.write("</p><span id=\"minutes\">00</span></div>\r\n");
      out.write("      <div class=\"time\"><p>");
      out.print(showlanguage.get("index.banner1.7"));
      out.write("</p><span id=\"seconds\">00</span></div>\r\n");
      out.write("    </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"carousel-item\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row p-5\">\r\n");
      out.write("                        <div class=\"mx-auto col-md-8 col-lg-6 order-lg-last\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"./assets/img/Banner2.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-6 mb-0 d-flex align-items-center\">\r\n");
      out.write("                            <div class=\"text-align-left\">\r\n");
      out.write("                                <h2 >");
      out.print(showlanguage.get("index.banner2.1"));
      out.write("</h2>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                   ");
      out.print(showlanguage.get("index.banner2.2"));
      out.write("\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"carousel-item\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row p-5\">\r\n");
      out.write("                        \r\n");
      out.write("                            <img class=\"img-fluid\" src=\"./assets/img/Banner4.jpg\" style=\"width:350px;height:400px;position:relative;left:100px\" alt=\"\">\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"col-lg-6 mb-0 d-flex align-items-center\">\r\n");
      out.write("                            <div class=\"text-align-right\" style=\"width:500px;position:absolute;left:700px\">\r\n");
      out.write("                               <h2>");
      out.print(showlanguage.get("index.banner3.1"));
      out.write("</h2>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                  ");
      out.print(showlanguage.get("index.banner3.2"));
      out.write("\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a class=\"carousel-control-prev text-decoration-none w-auto ps-3\" href=\"#template-mo-zay-hero-carousel\"\r\n");
      out.write("          role=\"button\" data-bs-slide=\"prev\">\r\n");
      out.write("            <i class=\"fas fa-chevron-left\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"carousel-control-next text-decoration-none w-auto pe-3\" href=\"#template-mo-zay-hero-carousel\"\r\n");
      out.write("          role=\"button\" data-bs-slide=\"next\">\r\n");
      out.write("            <i class=\"fas fa-chevron-right\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- End Banner Hero -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Start Categories of The Month -->\r\n");
      out.write("    <section class=\"container py-5\">\r\n");
      out.write("        <div class=\"row text-center pt-3\">\r\n");
      out.write("            <div class=\"col-lg-6 m-auto\">\r\n");
      out.write("                <h1 class=\"h1\">");
      out.print(showlanguage.get("index.category"));
      out.write("</h1>\r\n");
      out.write("                <p>\r\n");
      out.write("                    ");
      out.print(showlanguage.get("index.category2"));
      out.write("\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-12 col-md-4 p-5 mt-3\">\r\n");
      out.write("                <a href=\"#\"><img\r\n");
      out.write("                      src=\"https://product.hstatic.net/1000360860/product/tra_sua_toco_517ae6b8d48942a3b0ff7f40fbe2fcc2_master.jpg\"\r\n");
      out.write("                      class=\"rounded-circle img-fluid border\"></a>\r\n");
      out.write("                <h5 class=\"text-center mt-3 mb-3\">");
      out.print(showlanguage.get("index.category3"));
      out.write("</h5>\r\n");
      out.write("                <p class=\"text-center\"><a class=\"btn btn-success\">Go Shop</a></p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-12 col-md-4 p-5 mt-3\">\r\n");
      out.write("                <a href=\"#\"><img src=\"https://image.freepik.com/free-photo/pouring-coffee-with-smoke-cup-coffee-beans-burlap-sack-black-background_126277-480.jpg\" class=\"rounded-circle img-fluid border\"></a>\r\n");
      out.write("                <h2 class=\"h5 text-center mt-3 mb-3\">");
      out.print(showlanguage.get("index.category4"));
      out.write("</h2>\r\n");
      out.write("                <p class=\"text-center\"><a class=\"btn btn-success\">Go Shop</a></p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-12 col-md-4 p-5 mt-3\">\r\n");
      out.write("                <a href=\"#\"><img src=\"https://images8.alphacoders.com/746/thumb-1920-746166.jpg\" class=\"rounded-circle img-fluid border\"></a>\r\n");
      out.write("                <h2 class=\"h5 text-center mt-3 mb-3\">");
      out.print(showlanguage.get("index.category5"));
      out.write("</h2>\r\n");
      out.write("                <p class=\"text-center\"><a class=\"btn btn-success\">Go Shop</a></p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- End Categories of The Month -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Start Featured Product -->\r\n");
      out.write("    <section class=\"bg-light\">\r\n");
      out.write("        <div class=\"container py-5\">\r\n");
      out.write("            <div class=\"row text-center py-3\">\r\n");
      out.write("                <div class=\"col-lg-6 m-auto\">\r\n");
      out.write("                    <h1 class=\"h1\">");
      out.print(showlanguage.get("index.Feature"));
      out.write("</h1>\r\n");
      out.write("                    <p>\r\n");
      out.write("                      ");
      out.print(showlanguage.get("index.Feature2"));
      out.write("\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12 col-md-4 mb-4\">\r\n");
      out.write("                    <div class=\"card h-100\">\r\n");
      out.write("                        <a href=\"shop-single.html\">\r\n");
      out.write("                            <img src=\"./assets/img/Coffee1black.jpg\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <ul class=\"list-unstyled d-flex justify-content-between\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"text-muted text-right\">$20.00</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <a href=\"shop-single.html\" class=\"h2 text-decoration-none text-dark\">");
      out.print(showlanguage.get("index.Feature3"));
      out.write("</a>\r\n");
      out.write("                            <p class=\"card-text\">\r\n");
      out.write("                                ");
      out.print(showlanguage.get("index.Feature6"));
      out.write("\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p class=\"text-muted\"></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-12 col-md-4 mb-4\">\r\n");
      out.write("                    <div class=\"card h-100\">\r\n");
      out.write("                        <a href=\"shop-single.html\">\r\n");
      out.write("                            <img src=\"./assets/img/MilkTea1.jpg\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <ul class=\"list-unstyled d-flex justify-content-between\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"text-muted text-right\">$20.00</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <a href=\"shop-single.html\" class=\"h2 text-decoration-none text-dark\">");
      out.print(showlanguage.get("index.Feature2"));
      out.write("</a>\r\n");
      out.write("                            <p class=\"card-text\">\r\n");
      out.write("                                ");
      out.print(showlanguage.get("index.Feature7"));
      out.write("\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p class=\"text-muted\"></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-12 col-md-4 mb-4\">\r\n");
      out.write("                    <div class=\"card h-100\">\r\n");
      out.write("                        <a href=\"shop-single.html\">\r\n");
      out.write("                            <img src=\"./assets/img/Coffee2milk.jpg\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <ul class=\"list-unstyled d-flex justify-content-between\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"text-muted text-right\">$20.00</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <a href=\"shop-single.html\" class=\"h2 text-decoration-none text-dark\">");
      out.print(showlanguage.get("index.Feature5"));
      out.write("</a>\r\n");
      out.write("                            <p class=\"card-text\">\r\n");
      out.write("                               ");
      out.print(showlanguage.get("index.Feature6"));
      out.write("\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p class=\"text-muted\"></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"text-align:right\">Số lượt truy cập ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${views}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- End Featured Product -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Start Footer -->\r\n");
      out.write("    <footer class=\"bg-dark\" id=\"tempaltemo_footer\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-4 pt-5\">\r\n");
      out.write("                    <h2 class=\"h2 text-success border-bottom pb-3 border-light logo\">Zay Shop</h2>\r\n");
      out.write("                    <ul class=\"list-unstyled text-light footer-link-list\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <i class=\"fas fa-map-marker-alt fa-fw\"></i>\r\n");
      out.write("                            123 Consectetur at ligula 10660\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <i class=\"fa fa-phone fa-fw\"></i>\r\n");
      out.write("                            <a class=\"text-decoration-none\" href=\"tel:010-020-0340\">010-020-0340</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <i class=\"fa fa-envelope fa-fw\"></i>\r\n");
      out.write("                            <a class=\"text-decoration-none\" href=\"mailto:info@company.com\">info@company.com</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-4 pt-5\">\r\n");
      out.write("                    <h2 class=\"h2 text-light border-bottom pb-3 border-light\">Products</h2>\r\n");
      out.write("                    <ul class=\"list-unstyled text-light footer-link-list\">\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Luxury</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Sport Wear</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Men's Shoes</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Women's Shoes</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Popular Dress</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Gym Accessories</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Sport Shoes</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-4 pt-5\">\r\n");
      out.write("                    <h2 class=\"h2 text-light border-bottom pb-3 border-light\">Further Info</h2>\r\n");
      out.write("                    <ul class=\"list-unstyled text-light footer-link-list\">\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Home</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">About Us</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Shop Locations</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">FAQs</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Contact</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row text-light mb-4\">\r\n");
      out.write("                <div class=\"col-12 mb-3\">\r\n");
      out.write("                    <div class=\"w-100 my-3 border-top border-light\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-auto me-auto\">\r\n");
      out.write("                    <ul class=\"list-inline text-left footer-icons\">\r\n");
      out.write("                        <li class=\"list-inline-item border border-light rounded-circle text-center\">\r\n");
      out.write("                            <a class=\"text-light text-decoration-none\" target=\"_blank\" href=\"http://facebook.com/\"><i\r\n");
      out.write("                                  class=\"fab fa-facebook-f fa-lg fa-fw\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"list-inline-item border border-light rounded-circle text-center\">\r\n");
      out.write("                            <a class=\"text-light text-decoration-none\" target=\"_blank\"\r\n");
      out.write("                              href=\"https://www.instagram.com/\"><i class=\"fab fa-instagram fa-lg fa-fw\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"list-inline-item border border-light rounded-circle text-center\">\r\n");
      out.write("                            <a class=\"text-light text-decoration-none\" target=\"_blank\" href=\"https://twitter.com/\"><i\r\n");
      out.write("                                  class=\"fab fa-twitter fa-lg fa-fw\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"list-inline-item border border-light rounded-circle text-center\">\r\n");
      out.write("                            <a class=\"text-light text-decoration-none\" target=\"_blank\"\r\n");
      out.write("                              href=\"https://www.linkedin.com/\"><i class=\"fab fa-linkedin fa-lg fa-fw\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-auto\">\r\n");
      out.write("                    <label class=\"sr-only\" for=\"subscribeEmail\">Email address</label>\r\n");
      out.write("                    <div class=\"input-group mb-2\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control bg-dark border-light\" id=\"subscribeEmail\"\r\n");
      out.write("                          placeholder=\"Email address\">\r\n");
      out.write("                        <div class=\"input-group-text btn-success text-light\">Subscribe</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"w-100 bg-black py-3\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row pt-2\">\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <p class=\"text-left text-light\">\r\n");
      out.write("                            Copyright &copy; 2021 Company Name\r\n");
      out.write("                            | Designed by <a rel=\"sponsored\" href=\"https://templatemo.com\"\r\n");
      out.write("                              target=\"_blank\">TemplateMo</a>\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- End Footer -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Start Script -->\r\n");
      out.write("    <script src=\"assets/js/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/jquery-migrate-1.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/templatemo.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/custom.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/countdown.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/Translate.js\"></script>\r\n");
      out.write("    <!-- <script>\r\n");
      out.write("   function debounce(func, threshold) {\r\n");
      out.write("    var timeout;\r\n");
      out.write("\r\n");
      out.write("    return function() {\r\n");
      out.write("        var context = this,\r\n");
      out.write("            args = arguments;\r\n");
      out.write("\r\n");
      out.write("        if (timeout) {\r\n");
      out.write("            clearTimeout(timeout);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        timeout = setTimeout(function() {\r\n");
      out.write("            func.apply(context, args);\r\n");
      out.write("\r\n");
      out.write("            timeout = null;\r\n");
      out.write("        }, threshold || 250);\r\n");
      out.write("    };\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var SessionTimeout = (function() {\r\n");
      out.write("    var session_duration = 10,\r\n");
      out.write("        session_timeout_id,\r\n");
      out.write("        logout_duration = 15, //15 minutes\r\n");
      out.write("        session_timeout_duration = (session_duration - logout_duration) * 1000,\r\n");
      out.write("        logout_id,\r\n");
      out.write("        logout_timeout_duration = logout_duration * 1000,\r\n");
      out.write("        events = 'keydown mousedown',\r\n");
      out.write("        notification_element;\r\n");
      out.write("\r\n");
      out.write("    return {\r\n");
      out.write("        init: function() {\r\n");
      out.write("            var that = this;\r\n");
      out.write("\r\n");
      out.write("            document.addEventListener(events.split(' ')[0], debounce(function () {\r\n");
      out.write("                that.handler.apply(that);\r\n");
      out.write("            }, 500));\r\n");
      out.write("            \r\n");
      out.write("            this.startIdleTimeout();\r\n");
      out.write("        },\r\n");
      out.write("\r\n");
      out.write("        handler: function() {                    \r\n");
      out.write("            // reset session timeout\r\n");
      out.write("            clearTimeout(session_timeout_id);\r\n");
      out.write("\r\n");
      out.write("            this.startIdleTimeout();\r\n");
      out.write("        },\r\n");
      out.write("      \r\n");
      out.write("        startIdleTimeout: function () {\r\n");
      out.write("            var that = this;\r\n");
      out.write("\r\n");
      out.write("            session_timeout_id = setTimeout(function () {\r\n");
      out.write("                that.idle.apply(that); \r\n");
      out.write("            }, session_timeout_duration);\r\n");
      out.write("        },\r\n");
      out.write("\r\n");
      out.write("        idle: function() {\r\n");
      out.write("            // create bar\r\n");
      out.write("            notification_element = this.createTimeoutNotification();\r\n");
      out.write("\r\n");
      out.write("            // display bar\r\n");
      out.write("            notification_element.style.display = 'block';\r\n");
      out.write("\r\n");
      out.write("            // remove events\r\n");
      out.write("            document.removeEventListener('keydown', this.handler);\r\n");
      out.write("            document.removeEventListener('mousedown', this.handler);\r\n");
      out.write("\r\n");
      out.write("            // start logout timeout\r\n");
      out.write("            this.startLogoutTimeout();\r\n");
      out.write("            \r\n");
      out.write("            // start logout countdown\r\n");
      out.write("            this.startLogoutCountdown();\r\n");
      out.write("\r\n");
      out.write("            // add logout events\r\n");
      out.write("            this.attachTimeoutNotificationEvents();\r\n");
      out.write("        },\r\n");
      out.write("\r\n");
      out.write("        createTimeoutNotification: function() {\r\n");
      out.write("            var notification_element = document.createElement('div');\r\n");
      out.write("            notification_element.className = 'session-timeout-notification';\r\n");
      out.write("            notification_element.innerHTML = [\r\n");
      out.write("                '<strong>Hey!</strong> you will be logged off in <strong class=\"time\">' + logout_duration + '</strong> seconds due to inactivity. ',\r\n");
      out.write("                '<a href=\"#\">Click here to continue using www.example.com</a>'\r\n");
      out.write("            ].join('');\r\n");
      out.write("            \r\n");
      out.write("            document.body.appendChild(notification_element);\r\n");
      out.write("\r\n");
      out.write("            return notification_element;\r\n");
      out.write("        },\r\n");
      out.write("\r\n");
      out.write("        removeTimeoutNotification: function() {\r\n");
      out.write("            notification_element.style.display = 'none';\r\n");
      out.write("            document.body.removeChild(notification_element);\r\n");
      out.write("        },\r\n");
      out.write("\r\n");
      out.write("        attachTimeoutNotificationEvents: function() {\r\n");
      out.write("            var that = this,\r\n");
      out.write("                dismiss_element = notification_element.querySelector('a');\r\n");
      out.write("\r\n");
      out.write("            dismiss_element.addEventListener('click', function() {\r\n");
      out.write("                // reset timer to prevent logout\r\n");
      out.write("                clearTimeout(logout_id);\r\n");
      out.write("\r\n");
      out.write("                that.removeTimeoutNotification();\r\n");
      out.write("\r\n");
      out.write("                that.init();\r\n");
      out.write("            });\r\n");
      out.write("        },\r\n");
      out.write("\r\n");
      out.write("        startLogoutTimeout: function() {\r\n");
      out.write("            var that = this;\r\n");
      out.write("\r\n");
      out.write("            logout_id = setTimeout(function() {\r\n");
      out.write("                alert('REDIRECT:LOGOUT');\r\n");
      out.write("                \r\n");
      out.write("                that.removeTimeoutNotification.apply(that);\r\n");
      out.write("            }, logout_timeout_duration);\r\n");
      out.write("        },\r\n");
      out.write("\r\n");
      out.write("        startLogoutCountdown: function(time) {\r\n");
      out.write("            var that = this,\r\n");
      out.write("                time = time || logout_duration - 1;\r\n");
      out.write("\r\n");
      out.write("            setTimeout(function() {\r\n");
      out.write("                notification_element.querySelector('.time').innerHTML = time;\r\n");
      out.write("\r\n");
      out.write("                time--;\r\n");
      out.write("\r\n");
      out.write("                if (time > 0) {\r\n");
      out.write("                    that.startLogoutCountdown.call(that, time);\r\n");
      out.write("                }\r\n");
      out.write("            }, 1000);\r\n");
      out.write("        }\r\n");
      out.write("    };\r\n");
      out.write("}());\r\n");
      out.write("</script> -->\r\n");
      out.write("<!-- <script>\r\n");
      out.write("      // If the input checkbox is checked, activate dark mode by adding dark-class to the body\r\n");
      out.write("      $('#toggle').change(() => {\r\n");
      out.write("         if ($('#toggle').is(\":checked\")) {\r\n");
      out.write("            $(\"body\").addClass(\"dark-class\");\r\n");
      out.write("         } else {\r\n");
      out.write("            $(\"body\").removeClass(\"dark-class\")\r\n");
      out.write("         }\r\n");
      out.write("      })\r\n");
      out.write("   </script> -->\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("    <!-- End Script -->\r\n");
      out.write("</body>\r\n");
      out.write("    <style>\r\n");
      out.write("   .time-container {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("}\r\n");
      out.write(".time {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  flex-direction: column;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  margin: 0 15px;\r\n");
      out.write("  color: black;\r\n");
      out.write("  font-size: 1rem;\r\n");
      out.write("}\r\n");
      out.write(".time span {\r\n");
      out.write("  margin-top: 10px;\r\n");
      out.write("  color: black;\r\n");
      out.write("  font-size: 3rem;\r\n");
      out.write("}\r\n");
      out.write("@media screen and (max-width: 480px) {\r\n");
      out.write("  .time {\r\n");
      out.write("    font-size: 0.875rem;\r\n");
      out.write("    margin: 0 8px;\r\n");
      out.write("  }\r\n");
      out.write("  .time span {\r\n");
      out.write("    font-size: 1.75rem;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("      /* body {\r\n");
      out.write("         color: black;\r\n");
      out.write("         background-color: rgb(241, 241, 241);\r\n");
      out.write("         text-align: center;\r\n");
      out.write("         justify-content: center;\r\n");
      out.write("      }\r\n");
      out.write("      .dark-class {\r\n");
      out.write("         color: white;\r\n");
      out.write("         background-color: gray;\r\n");
      out.write("      }\r\n");
      out.write("      .dark-class section {\r\n");
      out.write("         color: white;\r\n");
      out.write("         background-color: gray;\r\n");
      out.write("      }\r\n");
      out.write("      p {\r\n");
      out.write("         font-size: 1.2rem;\r\n");
      out.write("      }\r\n");
      out.write("      .toggleButton {\r\n");
      out.write("         width: 3rem;\r\n");
      out.write("         height: 1.2rem;\r\n");
      out.write("         position: relative;\r\n");
      out.write("         display: inline-block;\r\n");
      out.write("      }\r\n");
      out.write("      .toggleButton input {\r\n");
      out.write("         opacity: 0;\r\n");
      out.write("      }\r\n");
      out.write("      .roundButton {\r\n");
      out.write("         background-color: black;\r\n");
      out.write("         top: 0;\r\n");
      out.write("         left: 0;\r\n");
      out.write("         position: absolute;\r\n");
      out.write("         right: 0;\r\n");
      out.write("         bottom: 0;\r\n");
      out.write("         cursor: pointer;\r\n");
      out.write("      }\r\n");
      out.write("      .roundButton:before {\r\n");
      out.write("         left: 0;\r\n");
      out.write("         bottom: 0;\r\n");
      out.write("         position: absolute;\r\n");
      out.write("         content: \"\";\r\n");
      out.write("         background-color: grey;\r\n");
      out.write("         transition: 1s;\r\n");
      out.write("         height: 20px;\r\n");
      out.write("         width: 20px;\r\n");
      out.write("      }\r\n");
      out.write("      input:checked+.roundButton {\r\n");
      out.write("         background-color: white;\r\n");
      out.write("      }\r\n");
      out.write("      input:checked+.roundButton:before {\r\n");
      out.write("         transform: translateX(2rem);\r\n");
      out.write("      }\r\n");
      out.write("      .roundButton.circle {\r\n");
      out.write("         border-radius: 20px;\r\n");
      out.write("      }\r\n");
      out.write("      .roundButton.circle:before {\r\n");
      out.write("         border-radius: 50%;\r\n");
      out.write("      }\r\n");
      out.write("   */\r\n");
      out.write("    </style>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/Web/index.jsp(81,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userName == 'PTT'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    \r\n");
          out.write("    ");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "HeaderAdmin.jsp", out, false);
          out.write("\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/Web/index.jsp(85,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userName != 'PTT'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    ");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
          out.write("\r\n");
          out.write("    \r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
