/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2024-02-29 02:19:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import DAO.NgonNguDAO;
import java.util.Map;
import java.util.HashMap;

public final class DangKy_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/LTWebCuoiKy/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DoAnWeb/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425953470000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1702995907573L));
    _jspx_dependants.put("jar:file:/D:/LTWebCuoiKy/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DoAnWeb/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425953470000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("DAO.NgonNguDAO");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.util.HashMap");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

  Map<String, String> showlanguage = new NgonNguDAO().vietnamLanguage();
  String lang = (String) session.getAttribute("lang1");
  if (lang != null) {
    if (lang.equals("Vietnamese")) {
      showlanguage = new NgonNguDAO().vietnamLanguage();
    } else if (lang.equals("English")) {
      showlanguage = new NgonNguDAO().englishLanguage();
    }
  }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Đăng ký</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!--   <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\"> -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css\">\r\n");
      out.write("\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css\" />\r\n");
      out.write(" <!--  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\">  -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("  \r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("        <link rel=\"shortcut icon\" href=\"favicon.png\">\r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- partial:index.partial.html -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"logo text-center\">\r\n");
      out.write("  <h1>Coffee&Tea</h1>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"wrapper\" id=\"wrap\">\r\n");
      out.write("  <div class=\"inner-warpper text-center\">\r\n");
      out.write("    <h2 class=\"title\">Sign up to your account</h2>\r\n");
      out.write("    <form action=\"XuLyDangKy\" method=\"post\">\r\n");
      out.write("      <div class=\"input-group\">\r\n");
      out.write("        <label class=\"palceholder\" for=\"username\">");
      out.print(showlanguage.get("DangKy.UserName"));
      out.write("</label>\r\n");
      out.write("        <input class=\"form-control\" name=\"username\" id=\"userName\" type=\"text\" placeholder=\"\" />\r\n");
      out.write("         <span style=\"color:red;font-size:10px\">");
      out.print(showlanguage.get("DangKy.Error"));
      out.write("</span>\r\n");
      out.write("        <span style=\"color:red;font-size:10px\">");
      out.print(showlanguage.get("DangKy.Error5"));
      out.write("</span>\r\n");
      out.write("        <span style=\"color:red;font-size:10px\">");
      out.print(showlanguage.get("DangKy.Error6"));
      out.write("</span>\r\n");
      out.write("        <span class=\"lighting\"></span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"input-group\">\r\n");
      out.write("        <label class=\"palceholder\" >");
      out.print(showlanguage.get("DangKy.PassWord"));
      out.write("</label>\r\n");
      out.write("        <input class=\"form-control\" name=\"pass\" id=\"pwd\" type=\"password\" placeholder=\"\" />\r\n");
      out.write("        <span style=\"color:red;font-size:10px\">");
      out.print(showlanguage.get("DangKy.Error3"));
      out.write("</span>\r\n");
      out.write("        <span style=\"color:red;font-size:10px\">");
      out.print(showlanguage.get("DangKy.Error4"));
      out.write("</span>\r\n");
      out.write("        <span class=\"lighting\" ></span>\r\n");
      out.write("        \r\n");
      out.write("          <button class=\"btn btn-outline-secondary\" type=\"button\" id=\"btnPassword\" style=\"height:40px\">\r\n");
      out.write("            <span class=\"fas fa-eye\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("    \r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"input-group\">\r\n");
      out.write("        <label class=\"palceholder\" for=\"userPassword\">");
      out.print(showlanguage.get("DangKy.RePass"));
      out.write("</label>\r\n");
      out.write("        <input class=\"form-control\" name=\"repass\" id=\"userPassword\" type=\"password\" placeholder=\"\"\r\n");
      out.write("        >\r\n");
      out.write("                 <span style=\"color:red;font-size:10px\">");
      out.print(showlanguage.get("DangKy.Error1"));
      out.write("</span>\r\n");
      out.write("        <span class=\"lighting\"></span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"input-group\">\r\n");
      out.write("        <label class=\"palceholder\" for=\"userPassword\">");
      out.print(showlanguage.get("DangKy.FirstName"));
      out.write("</label>\r\n");
      out.write("        <input class=\"form-control\" name=\"firstname\" id=\"userPassword1\" type=\"text\" placeholder=\"\" />\r\n");
      out.write("        <span class=\"lighting\"></span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"input-group\">\r\n");
      out.write("        <label class=\"palceholder\" for=\"userPassword\">");
      out.print(showlanguage.get("DangKy.Email"));
      out.write("</label>\r\n");
      out.write("        <input class=\"form-control\" name=\"email\" id=\"userPassword2\" type=\"email\" placeholder=\"\" />\r\n");
      out.write("        <span class=\"lighting\"></span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"input-group\">\r\n");
      out.write("        <label class=\"palceholder\" for=\"userPassword\">");
      out.print(showlanguage.get("DangKy.Telephone"));
      out.write("</label>\r\n");
      out.write("        <input class=\"form-control\" name=\"telephone\" id=\"userPassword3\" type=\"text\" placeholder=\"\" />\r\n");
      out.write("                 <span style=\"color:red;font-size:10px\">");
      out.print(showlanguage.get("DangKy.Error2"));
      out.write("</span>\r\n");
      out.write("        \r\n");
      out.write("        <span class=\"lighting\"></span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"input-group\">\r\n");
      out.write("        <label class=\"palceholder\" for=\"userPassword\">");
      out.print(showlanguage.get("DangKy.Address"));
      out.write("</label>\r\n");
      out.write("        <input class=\"form-control\" name=\"address\" id=\"userPassword4\" type=\"text\" placeholder=\"\" />\r\n");
      out.write("        <span class=\"lighting\"></span>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <button type=\"submit\" id=\"login\">");
      out.print(showlanguage.get("DangKy.SignUp"));
      out.write("</button>\r\n");
      out.write("      <br><br>\r\n");
      out.write("      <button onclick=\"event.preventDefault(); window.location.href='DangNhap.jsp';\" class=\"btn btn-success\">");
      out.print(showlanguage.get("DangKy.Login") );
      out.write("</button>\r\n");
      out.write("      <br><br>\r\n");
      out.write("      <button type=\"reset\">");
      out.print(showlanguage.get("DangKy.Reset"));
      out.write("</button>\r\n");
      out.write("      \r\n");
      out.write("    </form>\r\n");
      out.write("    <button onclick=\"openFullscreen();\">Open in Fullscreen Mode</button>\r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- you don't need that :)  -->\r\n");
      out.write("<div class=\"direction\" style=\"height:120px\">\r\n");
      out.write("  Type something in input and click submit to see the effect\r\n");
      out.write("  <ul class=\"dropdown-menu\" role=\"menu\" aria-labelledby=\"menu1\" style=\"list-style:none;text-align:center\">\r\n");
      out.write("    <li role=\"presentation\"><a role=\"menuitem\" href=\"DaNgonNguDKy?lang1=Vietnamese\"><img src=\"assets/img/vietnam.png\" style=\"position:relative;left:-30px\"></a></li>\r\n");
      out.write("<li role=\"presentation\"><a role=\"menuitem\" href=\"DaNgonNguDKy?lang1=English\"><img src=\"assets/img/united-states.png\" style=\"position:relative;left:-30px\"></a></li>\r\n");
      out.write("   \r\n");
      out.write("  </ul>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- partial -->\r\n");
      out.write("  <script src='https://code.jquery.com/jquery-2.2.4.min.js'></script>\r\n");
      out.write("<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.15.0/jquery.validate.min.js'></script><script  src=\"assets/js/script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script >\r\n");
      out.write("//step 1\r\n");
      out.write("const ipnElement = document.querySelector('#pwd')\r\n");
      out.write("const btnElement = document.querySelector('#btnPassword')\r\n");
      out.write("\r\n");
      out.write("// step 2\r\n");
      out.write("btnElement.addEventListener('click', function() {\r\n");
      out.write("  // step 3\r\n");
      out.write("  const currentType = ipnElement.getAttribute('type')\r\n");
      out.write("  // step 4\r\n");
      out.write("  ipnElement.setAttribute(\r\n");
      out.write("    'type',\r\n");
      out.write("    currentType === 'password' ? 'text' : 'password'\r\n");
      out.write("  )\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("/* Get the element you want displayed in fullscreen mode (a video in this example): */\r\n");
      out.write("var elem = document.getElementById(\"wrap\");\r\n");
      out.write("\r\n");
      out.write("/* When the openFullscreen() function is executed, open the video in fullscreen.\r\n");
      out.write("Note that we must include prefixes for different browsers, as they don't support the requestFullscreen method yet */\r\n");
      out.write("function openFullscreen() {\r\n");
      out.write("  if (elem.requestFullscreen) {\r\n");
      out.write("    elem.requestFullscreen();\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("    </script>\r\n");
      out.write("<style>\r\n");
      out.write("/* .container{\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),url(\"\");\r\n");
      out.write("	background-position: center;\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("} */\r\n");
      out.write("</style>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
